#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '
PATH=$PATH:~/.gem/ruby/2.1.0/bin/
alias music='/home/kobayashi/Scripts/music.sh'
alias gitpass='/home/kobayashi/gitpass.sh'
alias kpop='/home/kobayashi/Scripts/kpop.sh'
alias updatekpop='/home/kobayashi/Scripts/update_kpop.sh'
alias pause='mpc toggle'
alias p='mpc toggle'
alias kpopcount='/home/kobayashi/Scripts/kpop_count.sh'
