#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return
GREEN="\[$(tput setaf 2)\]"
RESET="\[$(tput sgr0)\]"
YELLOW="\[$(tput setaf 6)\]"
alias ls='ls --color=auto'
export PS1="[${GREEN}\u${RESET}@${YELLOW}\h${RESET} \W]\$ "
# Original PS1
#PS1='[\u@\h \W]\$ '
PATH=$PATH:~/.gem/ruby/2.1.0/bin/:~/Scripts/
export QUOTING_STYLE=literal
(wal -r &)
